version: '2'
services:
  rails:
    build:
      context: ./
      dockerfile: ./compose/rails/Dockerfile
    image: my/rails5.2
    container_name: 'rails'
    ports:
      - "80:3000"
    volumes:
      - rails-data:/usr/local/src

volumes:
  rails-data:
    driver_opts:
      type: none
      device: ${PWD}/src/
      o: bind
