version: '2'
services:
  rails:
    build:
      context: ./
      dockerfile: ./compose/rails/Dockerfile
    image: my/rails5.1
    container_name: 'rails'
    ports:
      - "80:3000"
    volumes:
      - app-rails:/usr/local/src
      # exclude volumes
      - /usr/local/src/app/vendor
      - /usr/local/src/app/tmp
      - /usr/local/src/app/log

volumes:
  app-rails:
    driver_opts:
      type: none
      device: ${PWD}/src/
      o: bind
